DATASET_NAME: "hotpotqa"
DATASET_SPLIT: "train"

TEXT_SPLITTER_CHUNK_SIZE: 1000
TEXT_SPLITTER_CHUNK_OVERLAP: 200

EMBEDDING_MODEL_NAME: "EMBEDDING_MODEL_NAME"
EMBEDDING_MODEL_MODEL_KWARGS: {}
EMBEDDING_MODEL_ENCODE_KWARGS: {}

WEAVIATE_URL: "{WEAVIATE_URL}"
WEAVIATE_API_KEY: "{WEAVIATE_API_KEY}"
